"""Turn the trained scikit-learn objects into the JSON files the Flutter app uses."""

import json
from pathlib import Path

import numpy as np

from genres import GENRES
from reference import ReferenceModel
from tokenizer import tokenize

# Numbers are stored to 7 decimal places. Full precision would roughly
# double the file size, and the rounding moves each probability by less
# than 1e-6. train.py checks that on every test plot.
DECIMALS = 7


def model_to_json(vectorizer, genre_names: list[str], models, thresholds, test_metrics: dict) -> dict:
    """Everything the app needs to predict, as plain lists and numbers.

    vocabulary[i], idf[i] and every genre's weights[i] all describe word i.
    """
    assert len(genre_names) == len(models) == len(thresholds)
    return {
        "format_version": 1,
        "about": ("Movie genre model: TF-IDF + one logistic regression per genre, "
                  "trained on the CMU Movie Summary Corpus (CC BY-SA). See README.md."),
        "vocabulary": vectorizer.get_feature_names_out().tolist(),
        "idf": _round_all(vectorizer.idf_),
        "genres": [
            {
                "name": name,
                "threshold": float(threshold),
                "intercept": round(float(model.intercept_[0]), DECIMALS),
                "weights": _round_all(model.coef_[0]),
            }
            for name, model, threshold in zip(genre_names, models, thresholds)
        ],
        "test_metrics": test_metrics,
    }


def parity_fixture(texts: list[str], probabilities: np.ndarray, thresholds: np.ndarray,
                   reference: ReferenceModel) -> dict:
    """What the app must output for each text, according to Python.

    Probabilities and yes/no decisions come straight from scikit-learn. Top
    words come from reference.py, because scikit-learn has no function that
    explains a prediction.
    """
    cases = []
    for text, row in zip(texts, probabilities):
        top_words = {result["genre"]: result["top_words"] for result in reference.predict(text)}
        cases.append({
            "text": text,
            "tokens": tokenize(text),
            "genres": [
                {
                    "name": name,
                    "probability": float(p),
                    "predicted": bool(p >= t),
                    "top_words": [[word, contribution] for word, contribution in top_words[name]],
                }
                for name, p, t in zip(GENRES, row, thresholds)
            ],
        })
    return {
        "about": ("Expected predictions from the Python model, generated by training/train.py. "
                  "test/parity_test.dart checks that the Dart code gives the same answers. "
                  "Plot texts are from the CMU Movie Summary Corpus (Wikipedia, CC BY-SA)."),
        "cases": cases,
    }


def rounded(data, digits: int = 6):
    """A copy of nested dicts and lists with every float cut to `digits`
    significant digits, for readable JSON. Significant digits rather than
    decimal places, so a tiny number like 4.1e-08 doesn't become 0."""
    if isinstance(data, float):
        return float(f"{data:.{digits}g}")
    if isinstance(data, dict):
        return {key: rounded(value, digits) for key, value in data.items()}
    if isinstance(data, list):
        return [rounded(value, digits) for value in data]
    return data


def write_json(data, path: Path, compact: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        if compact:
            json.dump(data, f, separators=(",", ":"))
        else:
            json.dump(data, f, indent=2)
        f.write("\n")


def _round_all(values) -> list[float]:
    return [round(float(v), DECIMALS) for v in values]
